=== api-evangelist/greynoise/json-schema/greynoise-time-series-intelligence-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://api-evangelist.github.io/greynoise/json-schema/greynoise-time-series-intelligence-schema.json",
  "title": "TimeSeriesIntelligence",
  "type": "object",
  "description": "Intelligence data for an IP in the timeseries dataset",
  "properties": {
    "first_seen": {
      "type": "string",
      "description": "The earliest date GreyNoise observed any activity from this IP.",
      "format": "date",
      "example": "2018-01-28"
    },
    "last_seen": {
      "type": "string",
      "description": "The most recent date GreyNoise observed any activity from this IP.",
      "format": "date",
      "example": "2018-02-28"
    },
    "found": {
      "type": "boolean",
      "description": "Indicates if the IP was observed scanning the GreyNoise sensor network. Also referred to as 'noise'.",
      "example": true
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "A list of activity/malware tags GreyNoise has applied to this\nIP.\n",
      "example": [
        "Mirai",
        "Telnet Worm"
      ]
    },
    "actor": {
      "type": "string",
      "description": "The overt actor this IP is associated with.",
      "example": "Shodan.io"
    },
    "spoofable": {
      "type": "boolean",
      "description": "This IP address has been opportunistically scanning the Internet, however has failed to complete a full TCP connection. Any reported activity could be spoofed.",
      "example": true
    },
    "classification": {
      "type": "string",
      "description": "The classification of the IP address, either \"benign\", \"malicious\", or \"unknown\", based on the activity observed by GreyNoise.",
      "enum": [
        "benign",
        "malicious",
        "unknown"
      ],
      "example": "benign"
    },
    "cves": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "A list of CVEs associate with this IP.",
      "example": [
        "CVE-2020-1234",
        "CVE-2021-2345"
      ]
    },
    "vpn": {
      "type": "boolean",
      "description": "This IP is associated with a VPN service. Activity, malicious or otherwise, should not be attributed to the VPN service provider.",
      "example": true
    },
    "vpn_service": {
      "type": "string",
      "description": "Name of associated VPN Service.",
      "example": "IPVANISH_VPN"
    },
    "tor": {
      "type": "boolean",
      "description": "Whether or not the device is a known Tor exit node.",
      "example": false
    },
    "last_seen_timestamp": {
      "type": "string",
      "description": "The timestamp of the last observed activity from this IP.",
      "format": "date-time",
      "example": "2025-01-15T12:30:45Z"
    },
    "metadata": {
      "$ref": "./greynoise-metadata-v3-schema.json#"
    },
    "raw_data": {
      "$ref": "./greynoise-time-series-raw-data-schema.json#"
    }
  }
}

=== api-evangelist/greynoise/examples/greynoise-time-series-intelligence-example.json
{
  "first_seen": "2018-01-28",
  "last_seen": "2018-02-28",
  "found": true,
  "tags": [
    "Mirai",
    "Telnet Worm"
  ],
  "actor": "Shodan.io",
  "spoofable": true,
  "classification": "benign",
  "cves": [
    "CVE-2020-1234",
    "CVE-2021-2345"
  ],
  "vpn": true,
  "vpn_service": "IPVANISH_VPN",
  "tor": false,
  "last_seen_timestamp": "2025-01-15T12:30:45Z",
  "metadata": {
    "mobile": false,
    "source_country": "United States",
    "source_country_code": "US",
    "source_city": "Seattle",
    "region": "Seattle",
    "organization": "DigitalOcean, LLC",
    "rdns": "crawl-66-249-79-17.googlebot.com",
    "asn": "AS521",
    "category": "education",
    "os": "Windows 7/8",
    "destination_countries": [
      "string"
    ],
    "destination_country_codes": [
      "US"
    ],
    "destination_cities": [
      "string"
    ],
    "destination_asns": [
      "string"
    ],
    "single_destination": true,
    "carrier": "AIS",
    "datacenter": "us-west-1",
    "domain": "example.com",
    "rdns_parent": "example.com",
    "rdns_validated": true,
    "latitude": 37.7749,
    "longitude": -122.4194,
    "sensor_count": 10,
    "sensor_hits": 10
  },
  "raw_data": {
    "scan": [],
    "ja3": [],
    "hassh": [],
    "http": {
      "md5": [
        "9764955b67107eeb9edfae76f429e783"
      ],
      "cookie_keys": [
        "expremotekey"
      ],
      "request_authorization": [
        "Bearer exampletoken",
        "Basic username:password"
      ],
      "request_cookies": [
        "session_id=1234567890"
      ],
      "request_header": [
        "Content-Type: application/json",
        "Accept: application/json"
      ],
      "method": [
        "GET",
        "POST",
        "PUT",
        "DELETE"
      ],
      "path": [
        "/robots.txt"
      ],
      "request_origin": [
        "111.111.1.1"
      ],
      "useragent": [
        "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)\n"
      ],
      "ja4h": [
        "ge11cn060000_4e59edc1297a_4da5efaf0cbd"
      ]
    },
    "source": {
      "bytes": 1024
    },
    "tls": {
      "cipher": [
        "TLS_AES_128_GCM_SHA256",
        "TLS_AES_256_GCM_SHA384"
      ],
      "ja4": [
        "t13d1516h2_8daaf6152771_02713d6af862"
      ]
    },
    "ssh": {
      "key": [
        "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1234567890"
      ],
      "ja4ssh": [
        "c76s76_c71s59_c0s0"
      ]
    },
    "tcp": {
      "ja4t": [
        "64240_2-1-3-1-1-4_1460_8"
      ],
      "ja4l": "1460_64"
    }
  }
}
